### ISSUE TITLE
matching should always be case insensitive

### ISSUE THREAD

**Issue by jeroen** [r-hub/sysreqs.app#5]
A string like `openssl` should also match `OpenSSL` or `Openssl` or `openSSL`. I don't see any downside to this, I don't think there are libraries with identical names but different case.

**Comment by gaborcsardi** [comment]
FWIW, openssl was only included as `OpenSSL`. :)

**Comment by gaborcsardi** [comment]
But it is case insensitive now: https://sysreqs.r-hub.io/map/openssl

```json
[{
  "openssl": {
      "sysreqs": "OpenSSL",
      "platforms": {
          "DEB": "libssl-dev",
          "OSX/brew": "openssl@1.1",
          "RPM": "openssl-devel"
      }
   }
}]
```

**Comment by jeroen** [comment]
Great! Now I can remove some regexes from the DB and just use strings.

**Comment by gaborcsardi** [comment]
I would not worry, regexes are just as good.
